public class Constants {
    public static final String EN_ATTENTE_DE_PREPARATION = '1';
    public static final String EN_COURS_DE_PREPARATION = '2';
    public static final String ANNULEE = '4'; 
    public static final String TERMINEE = '3';
    public static final String ACCOUNT = 'Account'; 
    public static final String CONTACT = 'Contact';
    public static final String CONTACT_POINT_ADDRESS = 'ContactPointAddress';
    
    public static final String PROSPECT = 'Prospect';
    public static final String CLIENT = 'Client';
    
    public static final String DRIVE = 'Drive'; 
    public static final String DRIVE_DEPORTE = 'Drive déporté';
    public static final String LIVRAISON = 'Livraison'; 
    
    public static final String ACTIF_ACHETANT = 'Actif_Achetant';
    public static final String AQUILON_SYNCHRONISATION_STATUS2 = '2';
    public static final String AQUILON_SYNCHRONISATION_STATUS3 = '3';
    public static final String TYPE_DE_CLIENT_A = 'A'; 
    public static final String TYPE_DE_CLIENT_B = 'B';
    public static final String TYPE_DE_CLIENT_C = 'C'; 

    public static final String EFFECTIVE_ACCOUNTID =  '000000000000000';
}