/**
* @author : Maud Vasseur - IBM Lille
* @date : 04/2021
* @description : Class to schedule the productMediaBatch 
* @TestClass : ProductMediaScheduleBatchable_TST
**/
public without sharing class ProductMediaScheduleBatchable implements Schedulable {
    public void execute(SchedulableContext sc) {
		//ProductMediaBatch classBatch = new ProductMediaBatch(); Edit By Marouane (9/03/2023), ProductMediaBatch is empty !!
        //Database.executeBatch(classBatch, 100);
    }
}